# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
# url: "https://mateusz-kluczek.github.io"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Mateusz Kluczek website

# Short description of your site
description: Mateusz Kluczek website

# --- Navigation bar options --- #

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
  name: Mateusz Kluczek


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
  
